# Generated by Django 5.1.4 on 2024-12-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user_delete_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="age",
            new_name="password",
        ),
    ]
