# Generated by Django 5.1.4 on 2024-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_currencydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("currency_name", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("rate", models.FloatField()),
                ("result", models.FloatField()),
                ("transaction_type", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="CurrencyData",
        ),
    ]
