# Generated by Django 5.1.4 on 2024-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_event_currency_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "som",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
    ]
